name: MCGI Production

on:
  push:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest
    
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ssh.mcgi.org.au
          username: u27-nmpjtziggxux
          key: ${{ secrets.KEY }}
          port: 18765
          script: |
             cd ~/www/dev.mcgi.org.au/public_html
             git pull origin main
             composer install
             php artisan migrate

  build:
    runs-on: ubuntu-latest
    needs: deployment
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - uses: "shivammathur/setup-php@v2"
      with:
        php-version: "8.2"
    - name: Install composer dependencies
      run: |
        composer install  
    - name: Create local changes
      run: |
        npm install && npm run build
    - name: SFTP uploader
      uses: wangyucode/sftp-upload-action@v2.0.2
      with:
        host: ssh.mcgi.org.au
        username: u27-nmpjtziggxux
        privateKey: ${{ secrets.KEY }}
        localDir: 'public/build'
        remoteDir: '~/www/dev.mcgi.org.au/public_html/public/build'
    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     branch: ${{ github.ref }}
