name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: composer install --ignore-platform-reqs
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Install node packages
      run: npm install && npm run build
    - name: Install lftp
      run: sudo apt-get update && sudo apt-get install -y lftp
    - name: Deploy files to Live server
      run: lftp -c "set ssl:verify-certificate false; open -u dev@mcgi.org.au,'Pcsoftnepal@123' ftp.mcgi.org.au; mirror -R --parallel=10 --exclude-glob node_modules/ --exclude-glob .git/ --exclude-glob .github/ -n -p -v --ignore-time . /dev.mcgi.org.au/public_html"
    
