name: MCGI Production

on:
  push:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ssh.mcgi.org.au
          username: u27-nmpjtziggxux
          key: ${{ secrets.KEY }}
          port: 18765
          script: |
            whoami
            # cd ~/dataalchemist
            # git pull origin main
            # docker stop appseed-app
            # # docker stop appseed-db
            # docker system prune -af
            # docker compose --env-file .env up -d appseed-app --build --force-recreate
