name: MCGI Production

on:
  push:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ssh.mcgi.org.au
          username: u27-nmpjtziggxux
          key: ${{ secrets.KEY }}
          port: 18765
          script: |
             cd ~/www/dev.mcgi.org.au/public_html
             git pull origin main
             composer install
             npm run build
             php artisan migrate
